# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'JJJComics' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JJJComics
  pod 'SnapKit','~> 4.0.0'

  target 'JJJComicsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JJJComicsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
